name: Coding Standards

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]
    tags: [ "*.*.*" ]

jobs:
  style:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v2

    - name: ✍  Check hlint and stylish
      run: |
        curl -sSL https://raw.github.com/ndmitchell/hlint/8e10b5143acf97fbdf9baff40ee2da93881e0bf8/misc/run.sh | sh -s .
        curl -sSL https://raw.github.com/input-output-hk/adrestia/7958e55b6a554f7514e2d29a92c144cc347cc91d/.haskell/stylish-haskell.sh | VERSION=v0.11.0.0 sh -s $(git ls-files '*.hs') -i
        if [ -z "$(git status --porcelain)" ]; then
            echo "No style errors detected."
        else
            echo "Style errors detected:"
            git diff
            exit 1
        fi
